apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        resources:
          requests: 
            cpu: 100m 
            memory: 128Mi 
          limits: 
            cpu: 250m
            memory: 256Mi
        image: registryubr8272.azurecr.io/tripinsights/userprofile:1.0
        ports:
          - name: userprofile
            containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        envFrom:
        - secretRef:
            name: appli-secret
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8084