apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tripviewer
        image: registryubr8272.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: ""
        - name: TRIPS_API_ENDPOINT
          value: ""
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
          - name: tripviewer
            containerPort: 8082
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
          initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  ports:
  - port: 8082
  selector:
    app: tripviewer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appli-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: tripviewer.aks-team8--rg-3-team8-f50d52-3beab19f.hcp.northeurope.azmk8s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tripviewer
            port: 
              number: 8082