apiVersion: apps/v1
kind: Deployment
metadata:
  name: appli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryubr8272.azurecr.io/tripinsights/poi:1.0
        env:
        - name: SQL_PASSWORD
          value: "yourStrong*Password1"
        - name: SQL_USER
          value: "sqladminuBr8272"
        - name: SQL_SERVER
          value: "sqlserverubr8272.database.windows.net"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
          - name: poi
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/poi/healthcheck
            port: 8080
          periodSeconds: 5
          initialDelaySeconds: 2