apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        resources:
          requests: 
            cpu: 100m 
            memory: 128Mi 
          limits: 
            cpu: 250m
            memory: 256Mi
        image: registryubr8272.azurecr.io/tripinsights/tripviewer:1.0
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
          initialDelaySeconds: 2
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api.svc.cluster.local"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api.svc.cluster.local"
        - name: BING_MAPS_KEY
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80