apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryubr8272.azurecr.io/tripinsights/poi:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        envFrom:
        - secretRef:
            name: appli-secret
        ports:
          - name: poi
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/poi/healthcheck
            port: 80
          periodSeconds: 5
          initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  ports:
  - port: 8080
  selector:
    app: poi