apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        resources:
          requests: 
            cpu: 100m 
            memory: 128Mi 
          limits: 
            cpu: 250m
            memory: 256Mi
        image: registryubr8272.azurecr.io/tripinsights/trips:1.0
        volumeMounts:
        - name: secrets-store
          mountPath: "/secrets"
          readOnly: true
        ports:
          - name: trips
            containerPort: 8081
        env:
        - name: OPENAPI_DOCS_URI
          value: "http://trips.api.svc.cluster.local"
        - name: DEBUG_LOGGING
          value: "true"
        - name: PORT
          value: '8081'
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: appli-secret-from-kv
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8081