apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryubr8272.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        envFrom:
        - secretRef:
            name: appli-secret
        ports:
          - name: userprofile
            containerPort: 8084
        livenessProbe:
          httpGet:
            path: api/user/healthcheck
            port: 80
          periodSeconds: 5
          initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - port: 8084
  selector:
    app: userprofile