kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: web-dev-edit
subjects:
- kind: Group
  namespace: dev
  name: 50224319-45fa-497c-b340-0c6cc88f2b23
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-dev-edit
subjects:
- kind: Group
  namespace: api
  name: 26c28a23-41de-4adc-b317-d13cd8a95f9e