apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: 
  name: appli-secret-from-kv
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: "45f965d7-ea86-4ef3-a1fd-bb095439593a"
    keyvaultName: "kv-team8"
    objects: |
      array:
        - |
          objectName: sql-password
          objectType: secret
        - |
          objectName: sql-user
          objectType: secret
        - |
          objectName: sql-server
          objectType: secret
        - |
          objectName: sql-db
          objectType: secret
    tenantId: "497ee203-99b0-4d14-836d-6a67f78e4945"
